name: Monitor Dependency Update Failures

# This action currently uses the NIGHTLY_TESTING secret, but could be moved to a separate secret.

on:
  workflow_run:
    workflows: ["continuous integration"]
    types:
      - completed
    branches:
      - 'update-dependencies-**'

jobs:
  monitor-failures:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - name: Dump
        run: echo "${{ github.event.workflow_run }}"
