name: Monitor Dependency Update Failures

# This action currently uses the NIGHTLY_TESTING secret, but could be moved to a separate secret.

on:
  workflow_run:
    workflows: ["continuous integration"]
    types:
      - completed
    # branches:
      # - 'update-dependencies-**'

jobs:
  monitor-failures:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - name: Dump
        uses: actions/github-script@v7
        with:
          script: console.log(context)

      - name: Smaller dump
        uses: actions/github-script@v7
        id: find_prs
        with:
          result-encoding: string
          script: |
            const owner = context.repo.owner, repo = context.repo.repo;
            let output = "❌ `lake update` [failed](" + context.payload.workflow_run.html_url + "). "
            //console.log(context.payload.workflow_run.html_url)
            //console.log()
            //console.log(context.payload.workflow_run.pull_requests)
            let prs = context.payload.workflow_run.pull_requests
            if (prs.length) {
              for (let pr of prs) {
                const { data: pullRequest } = await github.rest.pulls.get({
                  owner,
                  repo,
                  pull_number: pr.number,
                });
                //console.log(pullRequest.html_url);
                let xxx = await github.rest.issues.removeLabel({
                  owner,
                  repo,
                  issue_number: pr.number,
                  name: "auto-merge-after-CI",
                });
                console.log(xxx);

                output += "Found [PR " + pr.number + "](" + pullRequest.html_url + "). "
              }
            } else {
              output += "No PR found for this run!";
            }
            return output;

      - name: Get result
        run: echo "${{steps.find_prs.outputs.result}}"
